services:
  postgres:
    image: postgres:16-alpine
    container_name: powork_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: powork_user
      POSTGRES_PASSWORD: powork_pass
      POSTGRES_DB: powork_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U powork_user -d powork_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
